import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{Home,Flag,Trophy,Users,Images,MapPin,Calendar,ChevronRight,Upload,Menu,X,ChevronLeft,ChevronRight as Next,Clock,Camera}from'lucide-react';
import data from'./data.json';import'./style.css';
const nav=[['Koti',Home],['Matkat',Flag],['Historia',Clock],['Pelaajat',Users],['Galleria',Images]];
const trips=[{name:'Vidbynäs 2026',year:2026,date:'26.–27.9.2026',location:'Vidbynäs Golf, Ruotsi',participants:3,champion:'Antti Ikonen',scratch:'Miikka Pesola',image:'/photos/vidbynas-2026/020.jpg'}];
function Logo(){return <div className="logo"><div className="swflag"/><div className="logoCore"><small>SVERIGE GOLF TOUR</small><b>SGT</b><em>EST. 2026</em></div></div>}
function Drawer({open,onClose,setPage}){if(!open)return null;return <div className="drawerWrap" onClick={onClose}><aside className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={onClose}><X/></button><Logo/><h2>Sverige Golf Tour</h2>{nav.map(([n,I])=><button onClick={()=>{setPage(n);onClose()}}><I/>{n}</button>)}<div className="drawerRule"/><button><Upload/>Lisää kuvia</button><small>Ylläpito lisätään seuraavassa vaiheessa</small></aside></div>}
function Results(){return <><h2>Tulokset</h2><div className="resultGrid"><section className="panel"><label>PÄÄKISA · NET</label>{data.net.map((r,i)=><div className="row" key={r.name}><strong>{i+1}.</strong><span>{r.name}</span><b>{r.score}</b></div>)}</section><section className="panel"><label>SCRATCH</label>{data.gross.map((r,i)=><div className="row" key={r.name}><strong>{i+1}.</strong><span>{r.name}</span><b>{r.score}</b></div>)}</section></div><div className="sidegames">{data.side.map(g=><div className="mini" key={g.name}><label>{g.name}</label><b>{g.winner}</b><span>{g.score}</span></div>)}</div></>}
function Scorecard({r}){return <details className="score"><summary>{r.name} · par {r.par}</summary>{Object.entries(r.scores).map(([p,s])=><div className="scorePlayer" key={p}><b>{p}</b><div className="holes">{s.map((v,i)=><span key={i}><small>{i+1}</small>{v}</span>)}</div><strong>{s.reduce((a,b)=>a+b,0)}</strong></div>)}</details>}
function HomePage({setPage,openMenu}){return <><header><button className="menuBtn" onClick={openMenu}><Menu/></button><span>RUOTSI · GOLF · PERINTEET</span></header><section className="hero"><Logo/><h1>SVERIGE<br/>GOLF TOUR</h1><p>Golfia, kilpailua ja yhteisiä matkoja Ruotsissa</p></section><main><label className="eyebrow">VIIMEISIN MATKA</label><article className="trip homeTrip"><img src="/photos/vidbynas-2026/020.jpg" alt="Vidbynäs 2026"/><div className="tripShade"/><div className="tripContent"><i>2026</i><h2>Vidbynäs</h2><p><MapPin/> Vidbynäs Golf, Ruotsi</p><p><Calendar/> 26.–27.9.2026</p><p><Flag/> South Course & North Course</p><button onClick={()=>setPage('Matkat')}>Avaa matka <ChevronRight/></button></div></article><div className="champs"><article><Trophy/><small>TOUR CHAMPION</small><b>Antti Ikonen</b><span>150 NET</span></article><article><Trophy/><small>SCRATCH CHAMPION</small><b>Miikka Pesola</b><span>172 SCR</span></article></div><section className="next"><small>SEURAAVA MATKA</small><h2>Sverige 2027</h2><p>Kohde julkistetaan myöhemmin</p></section><Gallery preview setPage={setPage}/></main></>}
function TripDetail(){return <main className="inner"><h1>Vidbynäs 2026</h1><p className="muted">Vidbynäs Golf · 26.–27.9.2026</p><img className="cover" src="/photos/vidbynas-2026/020.jpg" alt="Vidbynäs"/><Results/><h2>Kierrokset</h2>{data.rounds.map(r=><Scorecard r={r} key={r.name}/>)}</main>}
function Trips(){const[selected,setSelected]=useState(null);if(selected)return <><button className="back" onClick={()=>setSelected(null)}><ChevronLeft/>Kaikki matkat</button><TripDetail/></>;return <main className="inner"><h1>Matkat</h1><p className="muted">Kaikki Sverige Golf Tour -matkat, uusin ensin.</p>{trips.map(t=><article className="tripList" onClick={()=>setSelected(t)} key={t.name}><img src={t.image}/><div><small>{t.year}</small><h2>{t.name}</h2><p>{t.date} · {t.participants} osallistujaa</p><span>Champion: {t.champion}</span></div><ChevronRight/></article>)}</main>}
function Lightbox({photos,index,setIndex,onClose}){useEffect(()=>{const f=e=>{if(e.key==='Escape')onClose();if(e.key==='ArrowRight')setIndex((index+1)%photos.length);if(e.key==='ArrowLeft')setIndex((index-1+photos.length)%photos.length)};window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f)},[index]);return <div className="lightbox" onClick={onClose}><button className="lbClose" onClick={onClose}><X/></button><button className="lbPrev" onClick={e=>{e.stopPropagation();setIndex((index-1+photos.length)%photos.length)}}><ChevronLeft/></button><img src={photos[index].src} onClick={e=>e.stopPropagation()}/><button className="lbNext" onClick={e=>{e.stopPropagation();setIndex((index+1)%photos.length)}}><Next/></button><div className="lbCount">{index+1} / {photos.length}</div></div>}
function Gallery({preview=false,setPage}){const[index,setIndex]=useState(null);let ps=preview?data.photos.slice(0,6):data.photos;return <section className={preview?'galleryBlock':'inner'}><div className="galleryTitle"><h2>{preview?'Viimeisimmät kuvat':'Galleria'}</h2>{preview&&<button className="link" onClick={()=>setPage('Galleria')}>Kaikki kuvat →</button>}</div>{!preview&&<div className="galleryFilter"><Flag/> Vidbynäs 2026 <span>{data.photos.length} kuvaa</span></div>}<div className="gallery">{ps.map((p,i)=><button className="photoBtn" onClick={()=>setIndex(i)} key={p.src}><img loading="lazy" src={p.src}/></button>)}</div>{index!==null&&<Lightbox photos={ps} index={index} setIndex={setIndex} onClose={()=>setIndex(null)}/>} {!preview&&<button className="upload"><Upload/> Lisää kuvia</button>}</section>}
function History(){return <main className="inner"><h1>Historia</h1><p className="muted">Matkat, osallistujat ja mestarit vuodesta 2026 alkaen.</p><div className="historyTable"><div className="historyHead"><span>Matka</span><span>Ajankohta</span><span>Osall.</span></div>{trips.map(t=><div className="historyRow" key={t.name}><div><b>{t.name}</b><small>Tour: {t.champion}<br/>Scratch: {t.scratch}</small></div><span>{t.date}</span><strong>{t.participants}</strong></div>)}</div><h2>Osallistumiset</h2>{data.players.map(p=><div className="rank" key={p}><strong>1</strong><span>{p}</span><b>1 matka</b></div>)}<h2>Mestaruusranking</h2><div className="champRank"><div><Trophy/><span>Miikka Pesola</span><b>3</b><small>1 scratch + 2 päiväpeliä</small></div><div><Trophy/><span>Antti Ikonen</span><b>1</b><small>1 Tour-mestaruus</small></div><div><Trophy/><span>Antti Ryynänen</span><b>0</b><small>mestaruuksia</small></div></div></main>}
function Players(){return <main className="inner"><h1>Pelaajat</h1>{data.players.map((x,i)=><article className="player" key={x}><div>{x.split(' ').map(a=>a[0]).join('')}</div><section><b>{x}</b><span>{i===0?'Tour Champion 2026':i===1?'Scratch Champion 2026':'Vidbynäs 2026 · 3. sija'}</span></section></article>)}</main>}
function App(){const[page,setPage]=useState('Koti'),[menu,setMenu]=useState(false);return <div className="app">{page==='Koti'?<HomePage setPage={setPage} openMenu={()=>setMenu(true)}/>:page==='Matkat'?<Trips/>:page==='Galleria'?<Gallery/>:page==='Historia'?<History/>:<Players/>}<Drawer open={menu} onClose={()=>setMenu(false)} setPage={setPage}/><nav>{nav.map(([n,I])=><button key={n} className={page===n?'active':''} onClick={()=>setPage(n)}><I/><span>{n}</span></button>)}</nav></div>};createRoot(document.getElementById('root')).render(<App/>);